name: Docker Build and Push

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - name: Build and push Docker image
        working-directory: ./build
        run: |
          docker build -t brokkolii/brokk-alpine:${{ github.sha }} .
          docker push brokkolii/brokk-alpine:${{ github.sha }}
          docker tag brokkolii/brokk-alpine:${{ github.sha }} brokkolii/brokk-alpine:latest
          docker push brokkolii/brokk-alpine:latest

